#!/usr/bin/env python3
"""
Generates every fixture in fixtures/ from ONE base clean email by mutating
exactly one thing per bad fixture — so a fixture can't drift out of sync
with what audit.py actually reads (research-claude's suggestion, 2026-09-04
cross-session thread on this build). Fixtures are checked into the repo as
plain .eml files a reader can open directly; re-running this script should
reproduce them byte-for-byte.

Run: python3 fixtures/generate_fixtures.py

Note: fixtures/not-an-email.txt is NOT generated by this script -- it's
hand-authored plain prose with deliberately zero email structure, which
makes it a poor fit for an EmailMessage-based generator (there's nothing
message-shaped to build). See fixtures/manifest.md § Non-email input.
"""
from email.message import EmailMessage
from pathlib import Path

FIXTURES_DIR = Path(__file__).resolve().parent

BASE_BODY = """Hi there,

Here's what's new at Sunrise Yoga Studio this October: three new class \
times added to our weekly schedule, plus a new outdoor sunrise flow series \
starting October 5th.

This is a promotional email from Sunrise Yoga Studio.

Sunrise Yoga Studio
123 Main Street, Suite 4
Austin, TX 78701

You can unsubscribe at any time by clicking here: \
https://sunriseyoga.example/unsubscribe
"""


def base_message(**overrides) -> EmailMessage:
    msg = EmailMessage()
    msg["From"] = overrides.get("from_", "Sunrise Yoga Studio <hello@sunriseyoga.example>")
    msg["Reply-To"] = overrides.get("reply_to", "hello@sunriseyoga.example")
    msg["To"] = "subscriber@example.com"
    msg["Subject"] = overrides.get("subject", "New class schedule for October")
    msg.set_content(overrides.get("body", BASE_BODY))
    return msg


def missing_from_header_message() -> EmailMessage:
    """A REAL email -- has To/Reply-To/Subject and a fully compliant body
    -- but no From header at all (structurally absent, not empty). Exercises
    check_header_accuracy()'s 'From missing' branch specifically, which is
    distinct from bad-header-mismatch.eml's 'Reply-To domain differs'
    branch -- the two are different code paths to the same rule and both
    deserve their own fixture. Also the fixture --judge-mode uses to prove
    a real-but-incomplete email still gets a genuine FAIL, not swallowed
    by the NotAnEmailError refusal meant for actual non-email garbage."""
    msg = base_message()
    del msg["From"]
    return msg


def messy_html_only_message() -> EmailMessage:
    """No text/plain part at all, table-layout address, HTML entities,
    and opt-out phrased as 'no longer receive these emails' instead of the
    word 'unsubscribe' — three real-world ESP-output patterns in one
    fixture, none of them present in the clean plain-text base. Everything
    here should still fully PASS: this proves the parser handles real
    marketing-email shape, not just clean synthetic text."""
    msg = EmailMessage()
    msg["From"] = "Sunrise Yoga Studio <hello@sunriseyoga.example>"
    msg["Reply-To"] = "hello@sunriseyoga.example"
    msg["To"] = "subscriber@example.com"
    msg["Subject"] = "New class schedule for October"
    msg.set_content(
        "<html><body>"
        "<p>New classes this October at Sunrise Yoga Studio.</p>"
        "<p>This is a promotional email from Sunrise Yoga Studio.</p>"
        "<table><tr><td>Sunrise&nbsp;Yoga&nbsp;Studio</td></tr>"
        "<tr><td>123&nbsp;Main&nbsp;Street,&nbsp;Suite&nbsp;4</td></tr>"
        "<tr><td>Austin,&nbsp;TX&nbsp;78701</td></tr></table>"
        "<p>Don&#39;t want these emails? "
        "<a href=\"https://sunriseyoga.example/u\">Click here</a> "
        "to no longer receive these emails.</p>"
        "</body></html>",
        subtype="html",
    )
    return msg


def messy_view_in_browser_message() -> EmailMessage:
    """multipart/alternative where the text/plain part is a near-empty
    'view in browser' stub (extremely common real ESP output — Mailchimp/
    Klaviyo/Kajabi all do this) and the real content lives only in the
    HTML part. A naive 'always prefer text/plain' parser reads only the
    stub and false-FAILs every check on a genuinely compliant email."""
    msg = EmailMessage()
    msg["From"] = "Sunrise Yoga Studio <hello@sunriseyoga.example>"
    msg["Reply-To"] = "hello@sunriseyoga.example"
    msg["To"] = "subscriber@example.com"
    msg["Subject"] = "New class schedule for October"
    msg.set_content(
        "View this email in your browser: https://sunriseyoga.example/view\n"
    )
    msg.add_alternative(
        "<html><body>"
        "<p>New classes this October at Sunrise Yoga Studio.</p>"
        "<p>This is a promotional email from Sunrise Yoga Studio.</p>"
        "<p>Sunrise Yoga Studio<br>123 Main Street, Suite 4<br>"
        "Austin, TX 78701</p>"
        "<p>You can unsubscribe at any time: "
        "<a href=\"https://sunriseyoga.example/u\">click here</a></p>"
        "</body></html>",
        subtype="html",
    )
    return msg


def clean_longform_commercial_pitch_message() -> EmailMessage:
    """A long-form, non-pushy commercial pitch (~280 words) -- the shape
    of real soft-sell marketing copy (a paid offer described honestly,
    'here's who this is and isn't for', an embedded plain-text URL, no
    urgency pressure) rather than a short clean.eml-style announcement.
    Tests parser + rule robustness against real-length, real-complexity
    prose. Everything here should still fully PASS: proves the pipeline
    holds up on genuinely long real-shaped copy, not just short synthetic
    text. Fictional content throughout (Sunrise Yoga Studio persona,
    fictional offer, fictional domain) -- built as a synthetic stand-in
    after an earlier real-derived draft of this same structural shape
    turned out to contain a real domain in its body copy and was
    correctly not used."""
    msg = EmailMessage()
    msg["From"] = "Sunrise Yoga Studio <hello@sunriseyoga.example>"
    msg["Reply-To"] = "hello@sunriseyoga.example"
    msg["To"] = "subscriber@example.com"
    msg["Subject"] = "For the few who want more than the weekly class"
    msg.set_content(
        "Hi there,\n\n"
        "By now you've either started trying the technique from last week's "
        "class -- or the week got away from you before you had a chance. "
        "Both are completely normal.\n\n"
        "Here's the honest split.\n\n"
        "For most people, what we covered in class is enough. You saw the "
        "sequence, you felt where it opens things up, and you can keep "
        "building on it at your own pace at home. That was the whole point "
        "of teaching it plainly -- so you don't need anything more from us. "
        "Keep practicing.\n\n"
        "For a few people, the constraint isn't knowing the sequence. It's "
        "that a weekend of focused, guided practice -- with an instructor "
        "actually watching your form the whole time -- gets you further in "
        "two days than months of solo practice would. If that sounds like "
        "you, there's a way to do that together. It's called the Fall "
        "Immersion Weekend: two days working directly with an instructor "
        "on your own practice, in a small group capped at eight people, "
        "because eight is how many people one instructor can actually "
        "watch closely across a full weekend.\n\n"
        "Let me be straight about what the weekend is and isn't: you leave "
        "with real corrections to your own form and a home practice built "
        "around your actual body -- not a certificate, not a title. If "
        "you're looking for a teacher-training credential, this isn't "
        "that; this is about your own practice getting better, guided.\n\n"
        "No pressure here. If you're curious how the weekend works, it's "
        "laid out plainly:\n\n"
        "sunriseyoga.example/fall-immersion\n\n"
        "I'll send one more short note about how to tell if this is "
        "actually worth your time -- most people's home practice is fine "
        "as it is, and I'll say so honestly.\n\n"
        "-- Sunrise Yoga Studio\n\n"
        "---\n"
        "This is a promotional email.\n"
        "Sunrise Yoga Studio, 123 Main Street, Suite 4, Austin, TX 78701\n"
        "Don't want these emails? Unsubscribe: "
        "https://sunriseyoga.example/unsubscribe\n"
    )
    return msg


FIXTURES = {
    "clean.eml": base_message(),

    "bad-header-mismatch.eml": base_message(
        reply_to="support@a-totally-different-domain.example",
    ),

    "bad-subject-contradicts-body.eml": base_message(
        subject="Re: Your Order Confirmation",
        body=(
            "Flash Sale: 30% off all classes this week! Buy now and save "
            "before it's gone.\n\n"
            "This is a promotional email from Sunrise Yoga Studio.\n\n"
            "Sunrise Yoga Studio\n"
            "123 Main Street, Suite 4\n"
            "Austin, TX 78701\n\n"
            "You can unsubscribe at any time by clicking here: "
            "https://sunriseyoga.example/unsubscribe\n"
        ),
    ),

    "bad-no-ad-disclosure.eml": base_message(
        body=(
            "Hi there,\n\n"
            "Here's what's new at Sunrise Yoga Studio this October: three "
            "new class times added to our weekly schedule, plus a new "
            "outdoor sunrise flow series starting October 5th.\n\n"
            "Sunrise Yoga Studio\n"
            "123 Main Street, Suite 4\n"
            "Austin, TX 78701\n\n"
            "You can unsubscribe at any time by clicking here: "
            "https://sunriseyoga.example/unsubscribe\n"
        ),
    ),

    "bad-no-postal-address.eml": base_message(
        body=(
            "Hi there,\n\n"
            "Here's what's new at Sunrise Yoga Studio this October: three "
            "new class times added to our weekly schedule, plus a new "
            "outdoor sunrise flow series starting October 5th.\n\n"
            "This is a promotional email from Sunrise Yoga Studio.\n\n"
            "You can unsubscribe at any time by clicking here: "
            "https://sunriseyoga.example/unsubscribe\n"
        ),
    ),

    "bad-no-optout.eml": base_message(
        body=(
            "Hi there,\n\n"
            "Here's what's new at Sunrise Yoga Studio this October: three "
            "new class times added to our weekly schedule, plus a new "
            "outdoor sunrise flow series starting October 5th.\n\n"
            "This is a promotional email from Sunrise Yoga Studio.\n\n"
            "Sunrise Yoga Studio\n"
            "123 Main Street, Suite 4\n"
            "Austin, TX 78701\n"
        ),
    ),

    "bad-fee-gated-optout.eml": base_message(
        body=(
            "Hi there,\n\n"
            "Here's what's new at Sunrise Yoga Studio this October: three "
            "new class times added to our weekly schedule, plus a new "
            "outdoor sunrise flow series starting October 5th.\n\n"
            "This is a promotional email from Sunrise Yoga Studio.\n\n"
            "Sunrise Yoga Studio\n"
            "123 Main Street, Suite 4\n"
            "Austin, TX 78701\n\n"
            "To unsubscribe, please pay a $5 processing fee at "
            "https://sunriseyoga.example/unsubscribe\n"
        ),
    ),

    "bad-multistep-optout.eml": base_message(
        body=(
            "Hi there,\n\n"
            "Here's what's new at Sunrise Yoga Studio this October: three "
            "new class times added to our weekly schedule, plus a new "
            "outdoor sunrise flow series starting October 5th.\n\n"
            "This is a promotional email from Sunrise Yoga Studio.\n\n"
            "Sunrise Yoga Studio\n"
            "123 Main Street, Suite 4\n"
            "Austin, TX 78701\n\n"
            "To unsubscribe, please call us at (555) 123-4567 or mail a "
            "letter to our office.\n"
        ),
    ),

    # Messy-but-compliant fixtures — same content as the base, shaped like
    # real-world ESP output rather than clean synthetic plain text. All of
    # these must fully PASS; see fixtures/manifest.md § Parser robustness.
    "missing-from-header.eml": missing_from_header_message(),

    "clean-html-only-entities.eml": messy_html_only_message(),
    "clean-view-in-browser-stub.eml": messy_view_in_browser_message(),
    "clean-longform-commercial-pitch.eml": clean_longform_commercial_pitch_message(),
}


def main():
    for filename, msg in FIXTURES.items():
        path = FIXTURES_DIR / filename
        path.write_bytes(bytes(msg))
        print(f"wrote {path.relative_to(FIXTURES_DIR.parent)}")


if __name__ == "__main__":
    main()
